### ISSUE TITLE
Replace checkbox by switch

### ISSUE THREAD

**Issue by jma** [rero/rero-ils-ui#37]
In all editors when a checkbox is used it can be themed by a switch:
https://getbootstrap.com/docs/4.2/components/forms/#switches

Note: can replace ngx-toogle-switch.

**Comment by iGormilhit** [comment]
An interesting short blog post about checkbox VS switch, when one is better than the other.

https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8
