### ISSUE TITLE
Group of issues found during test of rero-ils-ui

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils-ui#43]
**Software version**
RERO ILS: dev branch, commit https://github.com/rero/rero-ils/commit/0e71baa3507825a58496a68006f4ce9ba3e022e2
RERO ILS UI: US987 branch, commit https://github.com/rero/rero-ils-ui/commit/72a8e2c1c42091c07322f37e0b8f419a1f85296f

Tested on localhost:4200 with proxy configuration

## PUBLIC SEARCH

- [x] 1. Documents and persons : link to detail view raises an error despite proxy (base href is localhost:4200 instead of localhost:5000) -> zaa
- [x] 2. Documents : no result when filtering by library
- [x] 3. Persons : not filtered by source
- [x] 4. Public search no search input for persons. -> maj
- [x] 5. Facets in persons view should be open. -> zaa
- [x] 6. Some thumbnails are not displayed in org views (https://ilsdev.test.rero.ch/): unable to reproduce [zaa: seems to be fine now, perhaps a local glitch?]
7. Crashes when user modifies Redirect URL parameter `page` with value smaller than 1 manually: https://github.com/rero/rero-ils-ui/issues/75

## ADMIN

- [x] 4. Create new library : saving raises an error 403 (reroilstest+elena@gmail.com): zub
- [x] 5. Create new library : required field are not highlighted
- [x] 6. Editing opening hours of an existing library, submit is activated, no errors, but changes aren't visible. The JSON in the DB (accessed through the API) is not updated as wanted, and the detailed view do not reflect this, even with a hard refresh. Editing again the same record do not show the updated data in the editor: zub
- [x] 7. Create ci-po: saving raises an error 404 (localhost:4200) -> zaa
8. Add an item to a bibliographic record. Should be redirected to the bibliographic record. See https://github.com/rero/rero-ils/issues/376 : part of US985
- [x] 10. Validating a request in circulation module, the warning flash message as Search for title. -> zaa
- [x] 11. Person detail view doesn't work (OK after integrate PR https://github.com/rero/rero-ils/pull/659): zub
- [x] 13. Implement access control with permissions on object: zub
- [x] 14. Create a ci-po with settings. Edit the ci-po to remove settings then delete the ci-po from the detail view. This raises a 410 http error. (OK after integrate PR https://github.com/rero/ng-core/pull/74): zub
16. Cannot delete a freshly created circulation policy (contains parameters). Is it a normal behaviour?: [zaa: awaiting answer from PO group] -> https://github.com/rero/rero-ils-ui/issues/76
- [x] 17. Circulation Policies: search -> create and save -> detailed view. Back button return to the editor (new). Does this back button make sense (can be replaced in the detailed view by back to the search list) (OK after integrate PR https://github.com/rero/ng-core/pull/74): zub [mii: In some view, as the library detailed view, there a `back` link, and I think it's useless, and sometimes sensless]
- [x] 18. item_types is not translated as title of the editor. -> zaa
- [x] 19. Item types: search > create > detailed> delete (redirection to a new item type) (OK after integrate PR https://github.com/rero/ng-core/pull/74): zub
- [x] 20. The toaster message when a library is created/updated is not translated -> zaa
- [x] 21. A library can be create even if it is never open. Correct? [zub: correct]
22. Browser back button does not work at all in the admin view. [mii: it works for me, with firefox, zub: doesn't work on Chrome, zaa: works fine with Chrome excepted between brief views]: https://github.com/rero/rero-ils-ui/issues/77
- [x] 23. Patrons view: facet roles should be expanded: zub
- [x] 24. Patrons detailed view does not exists. Visible after Patron creation: zub
- [x] 25. reroilstest@gmail.com cannot edit an freshly created item for example: https://ilsdev.test.rero.ch/professional/records/documents/detail/13207 , but can remove it : critical -> zaa
- [x] 26. Display an empty holding array after item deletion in document detailed view -> zaa
- [x] 27. Mef facet source should be extended: zub
- [x] 28. Library detailed view code not well displayed. ->zaa
- [x] 29. New circulation policies > Cancel. Got a an error: `rero_ils_admin_ui.4706512e.js:2 POST https://ilsdev.test.rero.ch/api/circ_policies/ 400 (BAD REQUEST)` on console.log. (OK after integrate PR https://github.com/rero/ng-core/pull/74): zub [zaa : actually, this is fixed by https://github.com/rero/rero-ils-ui/pull/70]
- [x] 30. Query a resource from the search list update the header search input : maj -> https://github.com/rero/ng-core/pull/79
- [x] 31. Menus are not well translated. -> zaa
33. Changing the number of results fire two REST request (see network in the debug mode) : https://github.com/rero/rero-ils-ui/issues/78
- [x] 34. Author link to person on briefview doesn't work: zub
- [x ] 35. Cannot delete a freshly created item on document [zaa: unable to reproduce, already fixed?]
- [x] 36. Item view > Request section > Missing pickup location name : -> zaa
- [ x] 37. As a librarian, edit your own record, add yourself patron role, check data, and reedit yourself. Patron role is not checked. I've tried with Virgile, and also elrond@example.org in organisation 3 : to do [zaa + jma: unable to reproduce, already fixed?]
- [x] 38. Improve ci-po settings display in detail view -> zaa
- [x] 39. Bug on library form: Edit a library and after add new library (The form is populate with the previous library edit): zub
- [x] 40. 'No item' displayed in document brief view for records that does have item(s) -> zaa

## NG-CORE
- [x] 1. Document: Facets order: zub
- [x] 2. Document: Facet title translation: zub
- [x] 3. Document: Facet elements collapse: zub
- [x] 4. Language translate: zub
- [x] 5. Translate resource tab label for public search (OK after integrate PR https://github.com/rero/ng-core/pull/75): zub
- [x] 6. Don't allow to go to the end >> of a search (or you have to increase the ES `max_result_window`). Hide first and last link (OK after integrate PR https://github.com/rero/ng-core/pull/73). It is not possible to hide only last link (ngx-bootstrap pagination limitation): zub
- [x] 7. Lost space in a search view without facets (OK after integrate PR https://github.com/rero/rero-ils/pull/660 on reroils): zub

## AWAITING NEW FORM
1. Import from BnF does not get authors in the corresponding field. Tried with 9782218997495, author should be Hugo, Victor, 1802... -> jma + zaa : will be fixed with new editor

**Comment by iGormilhit** [comment]
@Garfield-fr 

2 screenshots related to 6:

Detailed view of library 9 (org 3):

![lib9-detailed](https://user-images.githubusercontent.com/1557213/70132074-59b45380-167b-11ea-8d07-d38b72a1bbcb.png)

Edition of the same library 9:

![lib9-edit](https://user-images.githubusercontent.com/1557213/70132073-59b45380-167b-11ea-8782-46680593765f.png)
