### ISSUE TITLE
Redirect URL parameter page manually set

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils-ui#75]
**Describe the issue**
Crashes when user modifies redirect URL parameter page with value smaller than 1 manually.

**To Reproduce**
Manually set parameter with value < 1

**Expected behavior**
TBD

**Software version**
v0.0.3

**Screenshots**
N/A

**Additional context**
N/A

**Comment by iGormilhit** [comment]
@AoNoOokami What is the status of this issue? Still relevant?

**Comment by AoNoOokami** [comment]
@iGormilhit It hasn't been addressed, as far as I know. But it's a really specific use case. It was reported by Peter.

**Comment by iGormilhit** [comment]
@AoNoOokami Ok.

@rerowep Can you explain this to me?
