### ISSUE TITLE
Is unique validation issue

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils-ui#93]
**Describe the issue**
Sometimes, when a resource is edited, there is an error message saying that the name is already used.

**To Reproduce**
1. Create an item with name = Itty test, description = Itty test
2. Create a second item with name = Itty test 2, description = Itty test
3. Try to edit the first item description (for example, add or remove a '.')
4. There is a validation error about the name

**Expected behavior**
As the name was not modified, it should not raise a validation error about name uniqueness

**Software version**
- ilsdev: https://github.com/rero/rero-ils/commit/b1bf8c01e6e515841659bed7c4daf257f732e602
- rero/dev: https://github.com/rero/rero-ils-ui/commit/d04ae97a9bfd47d73db76fc525dffe1a628d45f1

**Screenshots**
<img width="1113" alt="Screen Shot 2019-12-18 at 10 45 33" src="https://user-images.githubusercontent.com/28982829/71074990-986e0180-2183-11ea-9847-7f9775983458.png">

**Comment by iGormilhit** [comment]
Closed by release v0.6.0
